# версия Docker Compose
version: '3.8'

services:

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    image: shareit_gateway_image
    container_name: shareit_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      SHAREIT_SERVER_URL: http://server:9090
    networks:
      - shareit-net

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: shareit_server_image
    container_name: shareit_server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - shareit-net

  db:
    image: postgres:13.7-alpine
    container_name: shareit_db_container
    ports:
      - "6541:5432" # внешний:внутренний
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - shareit-net
networks:
  shareit-net:
    driver: bridge